### ISSUE TITLE
Make the todo list work

### ISSUE THREAD

**Issue by MSaurus** [MSaurus/new-tab-page#10]
It doesn't need to save anything at the time, it should just be simple
- [ ] Should be able to add todo
- [ ] Should be able to remove todo
- [ ] Should be able to mark a todo as done
- [ ] Should be able to unmark a done todo
